language: node_js

node_js: stable


branches:
  only:
    - source


cache:
  directories:
    - node_modules


before_install:
  - git config --global user.name "$USERNAME" 
  - git config --global user.email "$EMAIL"
  - git submodule init
  - git submodule update
  - sed "s+#leancloud-app-id+${leancloud-app-id}+g" themes/hexo-theme-next/_config.yml
  - sed "s+#leancloud-app-key+${leancloud-app-key}+g" themes/hexo-theme-next/_config.yml
  - sed "s+#livere-uid+${livere-uid}+g" themes/hexo-theme-next/_config.yml
  - sed "s+#swiftype-key+${swiftype-key}+g" themes/hexo-theme-next/_config.yml



install:
  - npm install


script:
  - hexo clean
  - hexo generate


after_script:
  - cd ./public
  - git init .
  - git add .
  - git commit -am "Travic Automated Update Blog"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
