# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Doublemine
subtitle:
description: Keep fucking the world
author: 夏末
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://notes.wanghao.work
root: /
# 设置永久链接
permalink: :year-:month-:day-:title.html
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
#category: 1
#tag: 1
#archive: 1
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: draft
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
#per_page: 5
pagination_dir: page

#自定义配置

index_generator:
  per_page: 5

archive_generator:
  per_page: 20
  yearly: true
  monthly: true

tag_generator:
  per_page: 10


# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: hexo-theme-next

# Deployment
## Docs: http://hexo.io/docs/deployment.html
deploy:
  type: git
  repo:
    github: git@github.com:Doublemine/Doublemine.github.io.git,master


rss:










creative_commons: by-nc-sa

since: 2015
social:
  Twitter: https://twitter.com/Mokasa__ || twitter
  Instagram: https://www.instagram.com/___xiamo/ || instagram
  GitHub: https://github.com/doublemine || github

#以下为友情链接
links_title: 友情链接
links:
  Kevin: https://www.labradors.work/
  kisence: http://www.kisence.com/
